name: Build main packages
description: Build Spring Boot API, Config server, and front npm packages

runs:
  using: "composite"
  steps:
    - name: Build API package
      shell: ${{ runner.os == 'Windows' && 'cmd' || 'sh' }}
      run: mvn -DfinalName=vglservice -T 1C -Dmaven.test.skip -DskipTests -Dmaven.javadoc.skip=true clean package -f vglservice/pom.xml

    - name: Build Config server package
      shell: ${{ runner.os == 'Windows' && 'cmd' || 'sh' }}
      run: mvn -DfinalName=vglconfig -T 1C -Dmaven.test.skip -DskipTests -Dmaven.javadoc.skip=true clean package -f vglconfig/pom.xml