version: "3"

services:
  vgldatabase:
    image: postgres:15.1-alpine
    restart: on-failure
    container_name: vgldatabase
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/vgl
    volumes:
      - vgldatabase:/data/vgl
    ports:
      - ${DB_PORT}:5432

  vglconfig:
    build: ./vglconfig
    image: vglconfig:1.0.10-SNAPSHOT
    restart: on-failure
    container_name: vglconfig
    environment:
      - GIT_CONFIG_REPOSITORY=${GIT_CONFIG_REPOSITORY}
      - GIT_CONFIG_BRANCH=${GIT_CONFIG_BRANCH:-master}
    ports:
      - ${CONFIG_SERVER_PORT}:8888

  vglservice:
    build: ./vglservice
    image: vglservice:2.6.2-SNAPSHOT
    restart: on-failure
    container_name: vglservice
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - ALLOWED_ORIGINS=${API_ALLOWED_ORIGINS}
    volumes:
      - ./vglservice/src/main/resources/application.properties:/usr/vglservice/application.properties
    ports:
      - ${API_SERVER_PORT}:8080
    depends_on:
      - vglconfig
      - vgldatabase

  vglservice-two:
    build: ./vglservice
    image: vglservice:2.6.2-SNAPSHOT
    restart: on-failure
    container_name: vglservice-two
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - ALLOWED_ORIGINS=${API_ALLOWED_ORIGINS}
    ports:
      - ${API_TWO_SERVER_PORT}:8080
    volumes:
      - ./vglservice/src/main/resources/application.properties:/usr/vglservice/application.properties
    depends_on:
      - vglconfig
      - vgldatabase

  vgldiscovery:
    build: ./vgldiscovery
    image: vgldiscovery:1.0.10-SNAPSHOT
    restart: on-failure
    container_name: vgldiscovery
    environment:
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
    ports:
      - ${DISCOVERY_SERVER_PORT}:9999
    volumes:
      - ./vgldiscovery/src/main/resources/application.properties:/usr/vgldiscovery/application.properties
    depends_on:
      - vglconfig

  vglloadbalancer:
    build: ./vglloadbalancer
    image: vglloadbalancer:1.2.7-SNAPSHOT
    restart: on-failure
    container_name: vglloadbalancer
    environment:
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - ALLOWED_ORIGINS=${LOADBALANCER_ALLOWED_ORIGINS}
    ports:
      - ${LOADBALANCER_SERVER_PORT}:10000
    volumes:
      - ./vglloadbalancer/src/main/resources/application.properties:/usr/vglloadbalancer/application.properties
    depends_on:
      - vglconfig
      - vgldiscovery
      - vglservice
      - vglservice-two

  vglfront:
    build: ./vglfront
    image: vglfront:0.5.3-SNAPSHOT
    restart: on-failure
    container_name: vglfront
    environment:
      - API_URL=${API_URL}
      - TEST_API_URL=${TEST_API_URL}
    volumes:
      - ./vglfront/src/assets:/usr/share/nginx/html/assets
      - ./vglfront/server/docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${FRONT_SERVER_PORT}:80
    depends_on:
      - vglservice
      - vgldiscovery
      - vglloadbalancer

volumes:
  vgldatabase: