package com.zemasterkrom.videogameslibraryapplication.dao;

import com.zemasterkrom.videogameslibraryapplication.model.VideoGame;
import org.springframework.data.repository.CrudRepository;
import org.springframework.lang.NonNull;

import java.util.Optional;
import java.util.Set;

/**
 * Interface of the video game DAO operations generated by the Spring Boot JPA
 */
public interface VideoGameRepository extends CrudRepository<VideoGame, Integer> {

    @NonNull
    Set<VideoGame> findAll();

    Optional<VideoGame> findByIdOrName(Integer id, String name);

    @NonNull
    Optional<VideoGame> findById(@NonNull Integer id);

    Optional<VideoGame> findByName(String name);

    boolean existsByIdOrName(Integer id, String name);

    boolean existsById(@NonNull Integer id);

    boolean existsByName(String name);

    void deleteByIdOrName(Integer id, String name);

    void deleteById(@NonNull Integer id);

    void deleteByName(String name);
}
