name: Build Load Balancing related packages
description: Build Eureka discovery server and Load Balancing server packages

runs:
  using: "composite"
  steps:
    - name: Build Load Balancing server package
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'sh' }}
      run: mvn -DfinalName=vglloadbalancer -T 1C clean package -f vglloadbalancer/pom.xml

    - name: Build Eureka discovery server package
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'sh' }}
      run: mvn -DfinalName=vgldiscovery -T 1C clean package -f vgldiscovery/pom.xml