name: Test API with Load Balancing
description: Test API with Load Balancing (without Docker and with Docker)

runs:
  using: "composite"
  steps:
    - name: Create environment file if not exists
      run: echo '' >> vglfront/.env
      shell: bash

    - name: Load environment file
      id: lb_env
      uses: falti/dotenv-action@v1.0.2

    - name: Load front environment file
      id: front_env
      uses: falti/dotenv-action@v1.0.2
      with:
        path: vglfront/.env

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: './vglfront/package-lock.json'

    - name: Set up Newman
      shell: ${{ runner.os == 'Windows' && 'cmd' || 'sh' }}
      run: npm install -g newman

    - name: Wait for API to be ready
      uses: emilioschepis/wait-for-endpoint@v1.0.3
      with:
        url: ${{ steps.lb_env.outputs.api_url }}/video-games/all
        timeout: 120000
        interval: 10000

    - name: Wait for front to be ready
      uses: emilioschepis/wait-for-endpoint@v1.0.3
      with:
        url: http://localhost:${{ steps.front_env.outputs.front_server_port }}/
        timeout: 120000
        interval: 10000

    - name: Run Postman tests on Spring Boot server (Load Balancer)
      shell: ${{ runner.os == 'Windows' && 'cmd' || 'sh' }}
      run: |
        newman run vglservice/src/test/collections/vgl_api_safe_data.json -e vglservice/src/test/environments/vgl_api_loadbalancer_endpoint.json
        newman run vglservice/src/test/collections/vgl_api_unsafe_data.json -e vglservice/src/test/environments/vgl_api_loadbalancer_endpoint.json