name: Build & test with Load Balancing
on: push

jobs:
  build-test-nlb:
    name: ${{ matrix.os }} - Build & test without Load Balancing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up CI/CD builders
        uses: ./.github/actions/setup

      - name: Build main components (API, Config server)
        uses: ./.github/actions/build-main

      - name: Change default front server port
        shell: bash
        run: echo $'\nFRONT_SERVER_PORT=4201' >> vglfront/.env

      - name: Run Config server
        run: java -DGIT_CONFIG_BRANCH=${{github.head_ref || github.ref_name}} -DGIT_CONFIG_REPOSITORY=https://github.com/Zemasterkrom/spring-cloud-video-games-api-config -XX:TieredStopAtLevel=1 -jar vglconfig/target/vglconfig.jar

      - name: Test curl
        shell: bash
        run: |
          sleep 50
          (echo 1 && curl 'http://localhost:8888/video-games-service.properties') || (echo 2 && curl 'http://127.0.0.1:8888/video-games-service.properties')

      - name: Run Spring Boot API
        run: java -DENABLE_LOAD_BALANCING=false -DALLOWED_ORIGINS=http://localhost:4201 -XX:TieredStopAtLevel=1 -jar vglservice/target/vglservice.jar

      - name: Test API and front
        uses: ./.github/actions/test-main