name: Build and test without Load Balancing
on: push

jobs:
  build-test-nlb:
    name: ${{ matrix.os }} - Build and test without Load Balancing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up CI/CD builders
        uses: ./.github/actions/setup

      - name: Build main components (API, Config server)
        uses: ./.github/actions/build-main

      - name: Change default front server port
        shell: bash
        run: echo $'\nFRONT_SERVER_PORT=4201' >> vglfront/.env

      - name: Run Config server
        run: java -DGIT_CONFIG_BRANCH=${{github.head_ref || github.ref_name}} -DGIT_CONFIG_REPOSITORY=https://github.com/Zemasterkrom/spring-cloud-video-games-api-config -XX:TieredStopAtLevel=1 -jar vglconfig/target/vglconfig.jar &

      - name: Run Spring Boot API
        run: java -DENABLE_LOAD_BALANCING=false -DALLOWED_ORIGINS=http://localhost:4201 -XX:TieredStopAtLevel=1 -jar vglservice/target/vglservice.jar &

      - name: Run npm front
        run: npm run start --prefix vglfront &

      - name: Test API and front
        uses: ./.github/actions/test-main

  build-test-nlb-docker:
    name: ${{ matrix.os }} - Build and test without Load Balancing (Docker)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Change default front server port
        shell: bash
        run: |
          echo $'\nFRONT_SERVER_PORT=4201' >> no-load-balancing.env
          echo $'\nAPI_ALLOWED_ORIGINS=http://localhost:4201' >> no-load-balancing.env

      - name: Install Docker on macOS
        if: runner.os == 'macOS'
        run: |
          brew install docker docker-machine docker-compose
          mkdir -p ~/.docker/cli-plugins
          ln -sfn $(brew --prefix)/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
          sudo docker-machine create --driver virtualbox default
          sudo docker-machine env default
          eval "$(docker-machine env default)"

      - name: Launch containers
        run: GIT_CONFIG_BRANCH=${{github.head_ref || github.ref_name}} docker compose --env-file no-load-balancing.env -f docker-compose-no-load-balancing.yml up -d --build

      - name: Test API and front
        uses: ./.github/actions/test-main